### ISSUE TITLE
problem['query'] Missing from the sample output file

### ISSUE THREAD

**Issue by YerongLi** [lupantech/MathVista#30]
https://github.com/lupantech/MathVista/pull/29

extract_answer.py is looking for problem['query'], however sample output does not contains such a field, does anyone know how to construct ['query'] strings?

https://github.com/lupantech/MathVista/blob/main/results/leaderboad_submission_template/output_testmini_template_for_leaderboard_submission.json

**Comment by YerongLi** [comment]
How problem['query'] is different from problem['question']?

**Comment by lupantech** [comment]
The ['query'] strings are part of the original dataset available at https://huggingface.co/datasets/AI4Math/MathVista.

Each ['query'] consists of two components: a task description that clarifies the type of question-answering task, and the actual question string.

For example, for `pid=1`:
- **Question**: "What is the total volume of the measuring cup?"
- **Query**: "Hint: Please answer the question requiring an integer answer and provide the final value, e.g., 1, 2, 3, at the end. Question: What is the total volume of the measuring cup? (Unit: g)"

Including the task description in the query is valuable because it guides models to generate responses in the expected format.

Additionally, you have the flexibility to structure the query content as you prefer.

The following link is provided as an example of a leaderboard submission, which is used for result verification: https://github.com/lupantech/MathVista/blob/main/results/leaderboad_submission_template/output_testmini_template_for_leaderboard_submission.json. Since you can design your own query format, it is not included here.

**Comment by YerongLi** [comment]
Could you merge https://github.com/lupantech/MathVista/blob/main/data/query.json to https://github.com/lupantech/MathVista/blob/main/data/testmini.json ?

https://github.com/lupantech/MathVista/blob/main/data/testmini.json Does not have ['query'] field.
