### ISSUE TITLE
Problem 781: Ambiguous Problem

### ISSUE THREAD

**Issue by mbchang** [lupantech/MathVista#4]
The correct answer choice of question 781 is ambiguous. The correct answer is 18, but this could refer to either the third or fourth choice.

<img width="279" alt="image" src="https://github.com/lupantech/MathVista/assets/6439365/074f11aa-ec8e-46a3-8669-c5a13ed8bd18">

**Comment by lupantech** [comment]
Thank you for pointing this out.

The issue you've noted originates from the source dataset, Geometry3K, which occasionally includes ambiguous information in its question choices.

Our evaluation framework is well-equipped to address this issue. It incorporates an [answer extractor](https://github.com/lupantech/MathVista/blob/main/evaluation/extract_answer.py) that thoroughly reviews both the raw question and the generated response. This tool specifically extracts the answer text (for example, “18” in the case of question 781), instead of relying on option labels like “C” or “D”.

Our [score calculator](https://github.com/lupantech/MathVista/blob/main/evaluation/calculate_score.py) then checks if the extracted answer text (e.g., “18”) matches the ground truth (also “18” in this instance). This approach ensures accuracy in scoring, effectively mitigating any ambiguity in the answer choices.
